### ISSUE TITLE
Confusion with miscommunication between `set_token()`  and `get_stored_token()`

### ISSUE THREAD

**Issue by howardbaek** [fhdsl/metricminer#35]
@cansavvy I'm confused as to why the `set_token()`  is setting  `options(google = token)` on [line 17](https://github.com/fhdsl/metricminer/blob/main/R/token-handlers.R#L17) and when we actually get the stored token in `get_stored_token()`, we use the [.RDS file](https://github.com/fhdsl/metricminer/blob/main/R/token-handlers.R#L71) instead of using the options that we set.

This confusion comes from adding `withr::local_options()` [here](https://github.com/fhdsl/metricminer/commit/a9b12f5c32720dfa7be7654361ab1939594244a1) and realizing that I can't use `withr::local_options()` for the Google Analytics functions because the token is stored in an RDS file, instead of an option.

**Comment by cansavvy** [comment]
Ah yes. Sorry I forgot to answer you in this. I think I've addressed the inconsistency on this other branch but it's not yet on a PR

It's here https://github.com/fhdsl/metricminer/blob/cansavvy/exports/R/token-handlers.R
